# NUMPY 

# creating Numpy arrays

In [1]:
# np .arrays
import numpy as np 

In [ ]:
# 1D 
a = np.array([1,2,3]) # Besically 1D is -> vector
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 2D 
b = np.array([[1,2,3],[4,5,6]]) # Besically 2D is -> Metrix
print(b)  # [[1 2 3], [4 5 6]]
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
# 3D 
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # Besically 3D is -> Tensor
print(c)  


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [23]:
# 4D 
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [7]:
# data type
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [8]:
# data type
np.array([1,2,3], dtype=bool)

array([ True,  True,  True])

In [9]:
# data type
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [10]:
# np.arange
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
# with reshape
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [16]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# np.ones and np.zeros -> use for intialization
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# np.random
np.random.random((3,4))

array([[0.048417  , 0.24153809, 0.57488393, 0.34298004],
       [0.82746871, 0.36019788, 0.26677642, 0.77057521],
       [0.16997848, 0.14452642, 0.91010834, 0.18856015]])

In [20]:
# np.linspace -> linearly separate in a given range 
np.linspace(-10,10,10) #1lower , 2uper, 3do want to genrate

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [22]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity , diognal 1 and all other are zero
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [44]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim -> tell the dimension 
a1.ndim

1

In [26]:
# ndim
a2.ndim

2

In [27]:
# ndim
a3.ndim

3

In [28]:
# shape
a1.shape

(10,)

In [33]:
# shape
a2.shape


(3, 4)

In [34]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [35]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
# size
a2.size

12

In [36]:
# size
a3.size

8

In [40]:
# item size 
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [45]:
a1.itemsize

4

In [46]:
a2.itemsize

8

In [47]:
a3.itemsize

8

In [48]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


# Changing dataype

In [50]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations 

In [53]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [58]:
# Scalar operations 

# arithmetic
a1 + 2 # 2 is sclar
 


array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:


# arithmetic
a1 * 2 # 2 is sclar
 

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [59]:
# relational
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [60]:
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [61]:
a2 > 30

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [62]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [63]:
a2 < 20

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [64]:
# Vector operations 

# arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [66]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [67]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [68]:
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Array Functions

In [69]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[10., 40., 20.],
       [33., 26., 84.],
       [27., 48., 75.]])

In [70]:
# max/min/sum/prod
np.max(a1)


np.float64(84.0)

In [71]:
# max/min/sum/prod
np.min(a1)

np.float64(10.0)

In [72]:
# max/min/sum/prod
np.sum(a1)

np.float64(363.0)

In [ ]:
# prod
np.prod(a1)

np.float64(56043187200000.0)

In [74]:
# max/min/sum/prod
# 0 -> column and 1 -> row
np.max(a1,axis=0)

array([33., 48., 84.])

In [75]:
# 0 -> column and 1 -> row
np.max(a1,axis=1)

array([40., 84., 75.])

In [76]:
# 0 -> column and 1 -> row
np.prod(a1,axis=0)

array([  8910.,  49920., 126000.])

In [77]:
#mean/median/std/var
np.mean(a1)

np.float64(40.333333333333336)

In [78]:
#mean/median/std/var
np.mean(a1,axis=1)

array([23.33333333, 47.66666667, 50.        ])

In [79]:
#mean/median/std/var
np.median(a1)

np.float64(33.0)

In [80]:
#mean/median/std/var
np.std(a1)

np.float64(23.423634787681152)

In [81]:
#mean/median/std/var
np.var(a1)

np.float64(548.6666666666666)

In [83]:
# trignometric function
np.sin(a1)

array([[-0.54402111,  0.74511316,  0.91294525],
       [ 0.99991186,  0.76255845,  0.73319032],
       [ 0.95637593, -0.76825466, -0.38778164]])

In [84]:
# trignometric function
np.cos(a1)

array([[-0.83907153, -0.66693806,  0.40808206],
       [-0.01327675,  0.64691932, -0.6800235 ],
       [-0.29213881, -0.64014434,  0.92175127]])

In [85]:
# trignometric function
np.tan(a1)

array([[  0.64836083,  -1.11721493,   2.23716094],
       [-75.3130148 ,   1.17875355,  -1.07818381],
       [ -3.2737038 ,   1.20012724,  -0.42070095]])

In [86]:
# Dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [87]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [89]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [90]:
# log and exponents
np.log(a1)

array([[2.30258509, 3.68887945, 2.99573227],
       [3.49650756, 3.25809654, 4.4308168 ],
       [3.29583687, 3.87120101, 4.31748811]])

In [91]:
# log and exponents
np.exp(a1)

array([[2.20264658e+04, 2.35385267e+17, 4.85165195e+08],
       [2.14643580e+14, 1.95729609e+11, 3.02507732e+36],
       [5.32048241e+11, 7.01673591e+20, 3.73324200e+32]])

In [93]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[72., 80., 14.],
       [22., 67.,  2.]])

In [94]:
# round/floor/ceil
np.floor(np.random.random((2,3))*100)

array([[61., 14., 86.],
       [ 6., 57., 65.]])

In [95]:
np.ceil(np.random.random((2,3))*100)

array([[54., 99., 64.],
       [59., 33., 16.]])

# Indexing and Slicing

In [96]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [97]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# last item 
a1[-1]

np.int64(9)

In [99]:
a1[0]

np.int64(0)

In [100]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
a2[1,2]

np.int64(6)

In [102]:
a2[2,3]

np.int64(11)

In [103]:
a2[1,0]

np.int64(4)

In [104]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [105]:
a3[1,0,1]

np.int64(5)

In [106]:
a3[0,1,0]

np.int64(2)

In [107]:
a3[0,0,0]

np.int64(0)

In [108]:
a3[1,1,0]

np.int64(6)

In [ ]:
# use slicing  in 1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
a1[2:5] # slicing

array([2, 3, 4])

In [111]:
# use slicing in 2D
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]  # 1st row 

array([0, 1, 2, 3])

In [ ]:
a2[:,2] # column

array([ 2,  6, 10])

In [114]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [115]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [120]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [122]:
a2[1,::3]

array([4, 7])

In [125]:
# 3D silicing\
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [126]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [127]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [129]:
a3[0,1,:]

array([3, 4, 5])

In [130]:
a3[1,:,1]

array([10, 13, 16])

In [131]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [132]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [136]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [137]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [138]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3): # print all the items 
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [140]:
# reshape

In [144]:
# Transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [145]:
# also use 
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [146]:

# ravel -> convert into 1D
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [148]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [151]:
# horizantal stacking 
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [152]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [153]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [154]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [155]:
# horizantal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [156]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [157]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vertical splitting - > you can not cut it into 2 parts if do they will show error 
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [159]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]